apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: api-account
  name: api-account
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-account
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: api-account
    spec:
      containers:
        - command:
            - ./wait-for-it.sh
          env:
            - name: JAVA_OPTS
              value: '"-Xmx150m"'
          image: jpstore_api-account
          name: api-account
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "262144e3"
      restartPolicy: Always
status: {}
