apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-account
  name: mysql-account
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-account
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-account
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_DATABASE
              value: jpetstore
            - name: MYSQL_PASSWORD
              value: test
            - name: MYSQL_ROOT_PASSWORD
              value: test
          image: mysql:8.0
          name: mysql-account
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: mysql-account-claim0
            - mountPath: /etc/mysql/my.cnf
              name: mysql-account-claim1
      restartPolicy: Always
      volumes:
        - name: mysql-account-claim0
          persistentVolumeClaim:
            claimName: mysql-account-claim0
        - name: mysql-account-claim1
          persistentVolumeClaim:
            claimName: mysql-account-claim1
status: {}
